import {
    BUTTON_BACKGROUNDBLUE, 
    BUTTON_BACKGROUNDRED,
    BUTTON_BACKGROUNDYELLOW,
    BUTTON_BACKGROUNDDARKGREEN,
    BUTTON_BACKGROUNDGREY
} 
from './index';

const actionTypes = {BUTTON_BACKGROUNDBLUE, BUTTON_BACKGROUNDRED, BUTTON_BACKGROUNDYELLOW, BUTTON_BACKGROUNDDARKGREEN,BUTTON_BACKGROUNDGREY};

export default actionTypes;