export const BUTTON_BACKGROUNDBLUE = 'BUTTON_BACKGROUNDBLUE';
export const BUTTON_BACKGROUNDRED = 'BUTTON_BACKGROUNDRED';
export const BUTTON_BACKGROUNDYELLOW = 'BUTTON_BACKGROUNDYELLOW';
export const BUTTON_BACKGROUNDDARKGREEN = 'BUTTON_BACKGROUNDDARKGREEN';
export const BUTTON_BACKGROUNDGREY = 'BUTTON_BACKGROUNDGREY';

